### ISSUE TITLE
crashed when testing/serving locally

### ISSUE THREAD

**Issue by stefanpenner** [translationexchange/ember-tml#4]
```
git clone https://github.com/translationexchange/ember-tml
cd ember-tml
npm i
bower i
npm run test
```

```
> ember-tml@0.2.6 test /Users/spenner/src/translationexchange/ember-tml
> ember try:testall

module.js:472
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:18:20
    at Object.<anonymous> (/Users/spenner/src/translationexchange/ember-tml/node_modules/ember-cli/node_modules/configstore/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

**Comment by stefanpenner** [comment]
```
ember s --port 4201
module.js:472
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:18:20
    at Object.<anonymous> (/Users/spenner/src/translationexchange/ember-tml/node_modules/ember-cli/node_modules/configstore/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

**Comment by berk** [comment]
This is no longer an issue in the new version. Fixed!
